name: Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: Decide Build Number
        id: decide_build_number
        run: | 
          VERSION=$(grep -oP "archiveVersion = '[^']+" build-jar.gradle | sed "s/archiveVersion = '//")
          echo "Found version: $VERSION"
          echo "marketing_build_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get Branch Name (Manual Build)
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" > branchBuild.properties

      - name: Get Branch Name (Pull Request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_HEAD_REF})" > branchBuild.properties

      - name: Invoke Gradle for aar
        run: |
          chmod +x gradlew 
          ./gradlew --console plain clean build assemble -x test
      
      - name: Archive aar file
        uses: actions/upload-artifact@v3
        env:
          MARKETING_VERSION: ${{ steps.decide_build_number.outputs.marketing_build_version }}
        with:
          name: 'cumulocity-clients-kotlin-${{ env.MARKETING_VERSION }}'
          path: 'build/outputs/aar/*.aar'

      - name: Invoke Gradle for jar
        run: |
          chmod +x gradlew 
          ./gradlew --console plain -b build-jar.gradle clean build -x test
      
      - name: Archive jar file
        uses: actions/upload-artifact@v3
        env:
          MARKETING_VERSION: ${{ steps.decide_build_number.outputs.marketing_build_version }}
        with:
          name: 'cumulocity-clients-kotlin-${{ env.MARKETING_VERSION }}'
          path: 'build/libs/*.jar'
