name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download version
        uses: actions/download-artifact@v3
        with:
          name: version

      - name: Set version as env variable
        id: set_build_number
        run: |
          echo "marketing_build_version=$(cat version.txt)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.marketing_build_version }}
          release_name: Release ${{ env.marketing_build_version }}
          body: |
            New release of the generated Kotlin client.
          draft: false
          prerelease: false
          
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: cumulocity-client-kotlin-jar
          path: artifacts

      - name: show downloaded content
        run: |
          ls -lsa artifacts/

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          MARKETING_VERSION: ${{ steps.set_build_number.outputs.marketing_build_version }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: "cumulocitycorelibrary-${{ env.marketing_build_version }}.jar"
          asset_path: artifacts/cumulocitycorelibrary-${{ env.marketing_build_version }}.jar
          asset_content_type: application/zip
