name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download version
        uses: actions/download-artifact@v3
        with:
          name: version

      - name: Set version as env variable
        run: |
          echo "marketing_build_version=$(cat version.txt)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          MARKETING_VERSION: ${{ steps.decide_build_number.outputs.marketing_build_version }}
        with:
          tag_name: v${{ env.MARKETING_VERSION }}
          release_name: Release ${{ env.MARKETING_VERSION }}
          body: |
            New release of the generated Kotlin client.
          draft: false
          prerelease: false
          
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: cumulocity-clients-kotlin-jar
          path: artifacts

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_name: "cumulocity-clients-kotlin-${{ env.MARKETING_VERSION }}.jar"
          asset_path: artifacts/cumulocity-clients-kotlin-${{ env.MARKETING_VERSION }}.jar
          asset_content_type: application/zip
